name = "misshaialert-worker"
main = "src/index.ts"
compatibility_date = "2025-08-14"

#kv_namespaces = [
#    { binding = "KV", id = "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa" }
#]

[triggers]

# will run at 15:10 UTC (0:10 JST)
crons = [ "10 15 * * *" ]

[vars]
#MISSKEY_HOST = "misskey.io"
#POST_VISIBILITY = "home"
#POST_TAGS = ["misshaialert"]
#DEBOBI = true